### ISSUE TITLE
de-duplicate CA from the trust bundle

### ISSUE THREAD

**Issue by Jiawei0227** [cert-manager/trust-manager#155]
It is possible that the trust bundle contains multiple sources which point to the same CA. It would be nice if we can dedup in the final trust bundle

**Comment by SgtCoDFish** [comment]
De-duplication is definitely a worthwhile thing to have in the case that we have two identical certificates in the resulting bundle. I've marked this as a good first issue in case anyone wanted to take a look - I think it'd be worth chatting about how we'd expose the API for this but it shouldn't be too hard to do this and save a few bytes!

**Comment by arsenalzp** [comment]
Hello,
Any deadlines for this issue? First of all I would like to examine entire project before start to work with even minor issue.

**Comment by SgtCoDFish** [comment]
> Any deadlines for this issue?

Not really, no! This feature would be a minor improvement which could save a little storage space, so it's not really a thing which we need in a hurry!

**Comment by arsenalzp** [comment]
I take it, please assign it to me!

**Comment by arsenalzp** [comment]
PR related to this issue was created.
Let's discuss about de-duplication method?
In my code I used hash `sha256` as unique signature of certificates; additional it's possible to check certificates serial numbers, however serial number might be set manually during signing CSR.
It is also possible to put  each certificate into `x509 Certificates Pool` then check uniqueness of each certificates against certificates in the pool; I decided to don't use this solution due to its memory consuming: `x509 Certificates Pool` consume much more memory than just a set of certificates hash sums, but it is possible to have hash collision, so let's discuss about solution in my PR.

**Comment by SgtCoDFish** [comment]
> PR related to this issue was created.

Amazing, great!

> Let's discuss about de-duplication method? In my code I used hash sha256 as unique signature of certificates

That's what I'd have done too. It's sometimes called the "sha256 fingerprint". The fingerprint is the way to do this - checking based on serial number or anything else is basically a subtle way of introducing little bugs IMO 😁

**Comment by erikgb** [comment]
I believe this was fixed by https://github.com/cert-manager/trust-manager/pull/184

/close
