### ISSUE TITLE
No flag to set structured logging format, e.g. JSON? 

### ISSUE THREAD

**Issue by smec42** [cert-manager/trust-manager#282]
Describe the bug:
In https://github.com/cert-manager/cert-manager/pull/5828 the option for setting the log-format to JSON was introduced to cert-manager. Is there a plan to enable this also for trust-manager?
Structured logging can be enabled in the pod spec.

**Comment by SgtCoDFish** [comment]
This is definitely something we'd like - I'm personally very enthusiasic about programs having solid logging with JSON support. Definitely consider this on the "roadmap"!

My gut instinct is for us to aggressively change to using `slog` wherever possible, because I like using the stdlib where we can. But I'm not dogmatic about that.

No timeline for this currently, but I think this should be a thing we do!

**Comment by arsenalzp** [comment]
I can tackle this once decision is approved, if you wish.
